version: "3.9"

services:
  rest_api:
    build:
      # set to directory where Dockerfile exists
      context: .
      dockerfile: Dockerfile
    # allows interactive debugging, dx
    tty: true
    env_file:
      - .env
    # maps host-port:container-port
    ports:
      - 4242:4242
    networks:
      - bb-network
    # ensures db service starts first
    depends_on:
      - db
    restart: on-failure

  db:
    # uses official postgres image
    image: postgres
    env_file:
      - .env
    # host-path:container-path
    # i.e. postgres-db is host path
    # /var/lib/postgresql/data is container path
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - bb-network

volumes:
  postgres-db:

networks:
  bb-network:
